name = "cloudflare-functions"
type = "javascript"

# Specify the output directory where the built files are located
pages_build_output_dir = "dist"  # or use 'public', or any directory you use for static files

# Define your Pages functions
[[functions]]
name = "submit"
path = "functions/submit.js"

# Environment and D1 database bindings
[env.production]
compatibility_date = "2025-03-11"
bindings = [
    { name = "D1_DATABASE", type = "d1", database_name = "testing1" }
]
